version: '3'

services:
  flask_app:
    container_name: flask_app
    build: ./flask_app
    ports:
      - "8000:8000"
    networks:
      - flask_network
    restart: always
    volumes:
      - ./log/flask:/flask_app/log # Flask Logs

  reverse_proxy:
    image: nginx:1.23.0
    container_name: reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask_app
    networks:
      - flask_network
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl/:/etc/ssl/
      - ./flask_app/app/static/:/etc/nginx/html/static/:ro
      - ./log/nginx:/var/log/nginx # NGINX Logs

  fail2ban:
    image: crazymax/fail2ban:0.11.2
    container_name: fail2ban
    network_mode: "host"
    depends_on:
      - flask_app
      - reverse_proxy
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./log/nginx/access.log:/var/log/nginx/access.log:ro
      - ./fail2ban/data:/data

networks:
  flask_network: